# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lieri\Documents\School_Folder\Junior\1140\power_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PowerUi(object):
    def setupUi(self, TestUi):
        TestUi.setObjectName("TestUi")
        TestUi.resize(465, 162)
        self.gridLayout = QtWidgets.QGridLayout(TestUi)
        self.gridLayout.setObjectName("gridLayout")
        self.kp_enter = QtWidgets.QLineEdit(TestUi)
        self.kp_enter.setObjectName("kp_enter")
        self.gridLayout.addWidget(self.kp_enter, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(TestUi)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(TestUi)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 0, 1, 1)
        self.ki_enter = QtWidgets.QLineEdit(TestUi)
        self.ki_enter.setObjectName("ki_enter")
        self.gridLayout.addWidget(self.ki_enter, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(TestUi)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(TestUi)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)

        self.retranslateUi(TestUi)
        QtCore.QMetaObject.connectSlotsByName(TestUi)

    def retranslateUi(self, TestUi):
        _translate = QtCore.QCoreApplication.translate
        TestUi.setWindowTitle(_translate("TestUi", "Form"))
        self.kp_enter.setText(_translate("TestUi", "5000"))
        self.label_17.setText(_translate("TestUi", "Kp:"))
        self.label_18.setText(_translate("TestUi", "Ki:"))
        self.ki_enter.setText(_translate("TestUi", "0"))
        self.pushButton.setText(_translate("TestUi", "Submit"))
        self.label.setText(_translate("TestUi", "KP and KI for Train 1:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TestUi = QtWidgets.QWidget()
    ui = Ui_PowerUi()
    ui.setupUi(TestUi)
    TestUi.show()
    sys.exit(app.exec_())
