# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'time_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Time(object):
    def setupUi(self, Time):
        Time.setObjectName("Time")
        Time.resize(193, 190)
        self.centralwidget = QtWidgets.QWidget(Time)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 171, 151))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        Time.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Time)
        self.statusbar.setObjectName("statusbar")
        Time.setStatusBar(self.statusbar)

        self.retranslateUi(Time)
        QtCore.QMetaObject.connectSlotsByName(Time)

    def retranslateUi(self, Time):
        _translate = QtCore.QCoreApplication.translate
        Time.setWindowTitle(_translate("Time", "MainWindow"))
        self.label.setText(_translate("Time", "Enter Time Multiplier"))
        self.label_2.setText(_translate("Time", "Current Time"))
        self.label_4.setText(_translate("Time", "Current Timer Multiplier"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Time = QtWidgets.QMainWindow()
    ui = Ui_Time()
    ui.setupUi(Time)
    Time.show()
    sys.exit(app.exec_())
