# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wayside_qtui_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10,60,261,141))
        self.label.setObjectName("label")#Error Messages and input codes
        self.tableView_5 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_5.setGeometry(QtCore.QRect(315, 10, 325, 200))
        self.tableView_5.setObjectName("tableView_5")#Maintenance orders
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 250, 600, 700))
        self.tableView.setObjectName("tableView")#block table
        self.tableView_2 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_2.setGeometry(QtCore.QRect(650, 250, 400, 350))
        self.tableView_2.setObjectName("tableView_2")#cross table
        self.tableView_3 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_3.setGeometry(QtCore.QRect(650, 600, 400, 350))
        self.tableView_3.setObjectName("tableView_3")#switch table
        self.tableView_4 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_4.setGeometry(QtCore.QRect(650, 10, 440, 200))
        self.tableView_4.setObjectName("tableView_4")#train authority and speed
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 160, 261, 20))
        self.lineEdit.setObjectName("lineEdit")#command input
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Green 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
